# Cocoapods Master Spec Repository
source 'https://github.com/CocoaPods/Specs.git'

# Project Settings
project 'Example'
platform :ios, '9.0'

# Project Options
inhibit_all_warnings!
use_frameworks!

target "Example" do
  pod "CellularRemoteConfiguration", :path => "../"
  pod "Alamofire", "~> 4.7"
  pod "Unbox", "~> 2.4.0"
  pod "OHHTTPStubs/Swift"
  pod "OHHTTPStubs", "~> 5.2.3"
end
