language: swift
osx_image: xcode11

# Build Script
before_script: chmod +x ./.travis/build.sh
script: ./.travis/build.sh

# Update Code Coverage
after_success: bash <(curl -s https://codecov.io/bash)

# Notifications
notifications:
    email: false
    slack:
        on_success: change
        rooms:
          - cellular:SnbeoVtpHMYrmikTbYz6OGdb#ios-informiert

# Build Matrix
matrix:
    include:
        # iOS
        - env: DESTINATION="OS=13.0,name=iPhone 11" POD_LINT="YES"
        - env: DESTINATION="OS=12.0,name=iPhone XS"
        - env: DESTINATION="OS=11.0.1,name=iPhone X"
        # watchOS
        - env: DESTINATION="OS=5.2,name=Apple Watch Series 4 - 44mm" RUN_TESTS="NO"
        - env: DESTINATION="OS=5.0,name=Apple Watch Series 2 - 42mm" RUN_TESTS="NO"
        # tvOS
        - env: DESTINATION="OS=13.0,name=Apple TV 4K"
        - env: DESTINATION="OS=12.0,name=Apple TV 4K (at 1080p)"
        - env: DESTINATION="OS=11.0,name=Apple TV"
